# Generated by Django 3.1.6 on 2021-02-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visitors', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Number of visitors',
            },
        ),
        migrations.AlterField(
            model_name='stats',
            name='ResponseTime',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='TimeStamp',
            field=models.DateTimeField(),
        ),
    ]
