# Generated by Django 3.1.6 on 2021-02-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210208_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='NumberOfAttempts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
